/* Patches */
#include "alpha.c"
#include "boxdraw.c"
#include "boxdraw_branch.c"
#include "boxdraw_common.c"
#include "boxdraw_extra.c"
#include "font2.c"
#include "fullscreen_x.c"
#include "keyboardselect_x.c"
#include "openurlonclick.c"
#include "osc8_x.c"
#include "undercurl.c"
#include "xresources.c"
