/* Patches */
#include "alpha.h"
#include "boxdraw.h"
#include "boxdraw_branch.h"
#include "boxdraw_common.h"
#include "boxdraw_extra.h"
#include "font2.h"
#include "fullscreen_x.h"
#include "keyboardselect_st.h"
#include "keyboardselect_x.h"
#include "xresources.h"
