#!/bin/sh
# Using external pipe with st, give a dmenu prompt of recent commands,
# allowing the user to copy the output of one.
# xclip required for this script.
# By Jaywalker and Luke

# We prefer to use GNU tools because they support UTF-8
AWK=$(command -v gawk); [ -z "$AWK" ] && AWK=awk
SED=$(command -v gsed); [ -z "$SED" ] && SED=sed
TAC=$(command -v gtac); [ -z "$TAC" ] && TAC=$(command -v tac)
[ -z "$TAC" ] && TAC="tail -r" # only works on BSD

tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
$SED -n "w $tmpfile"
$SED -i 's/\x0//g' "$tmpfile"
ps1="$(grep '[^[:space:]]' "$tmpfile" | tail -n 1 | $SED 's/^[[:space:]]*//' | cut -d' ' -f1)"
chosen="$(grep -F "$ps1" "$tmpfile" | $SED '$ d' | $TAC | dmenu -p "Copy which command's output?" -i -l 10 | $SED 's/[^^]/[&]/g; s/\^/\\^/g')"
eps1="$(echo "$ps1" | $SED 's/[^^]/[&]/g; s/\^/\\^/g')"
$AWK "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | xclip -selection clipboard
